automated_intelligence:
  target: dev
  outputs:
    dev:
      type: snowflake
      # Account and user are not needed when running in Snowflake
      # They will use the current session context
      account: 'not needed'
      user: 'not needed'
      role: AUTOMATED_INTELLIGENCE
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: staging  # Base schema (will be overridden by custom_schema in models)
      threads: 4
      client_session_keep_alive: False
      
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: AUTOMATED_INTELLIGENCE
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: staging  # Base schema (will be overridden by custom_schema in models)
      threads: 4
      client_session_keep_alive: False
