automated_intelligence:
  target: dev
  outputs:
    dev:
      type: snowflake
      # Account and user are not needed when running in Snowflake
      # They will use the current session context
      account: 'not needed'
      user: 'not needed'
      role: SNOWFLAKE_INTELLIGENCE_ADMIN
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: staging  # Base schema (will be overridden by custom_schema in models)
      threads: 4
      client_session_keep_alive: False
      
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SNOWFLAKE_INTELLIGENCE_ADMIN
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: staging  # Base schema (will be overridden by custom_schema in models)
      threads: 4
      client_session_keep_alive: False

    # GitHub Actions OIDC target (no secrets!)
    oidc:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      schema: staging
      threads: 4
      authenticator: WORKLOAD_IDENTITY
      workload_identity_provider: OIDC
      token: "{{ env_var('SNOWFLAKE_TOKEN') }}"
