automated_intelligence:
  target: dev
  outputs:
    dev:
      type: snowflake
      # Account and user are not needed when running in Snowflake
      # They will use the current session context
      account: 'not needed'
      user: 'not needed'
      role: SNOWFLAKE_INTELLIGENCE_ADMIN
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: dbt_staging
      threads: 4
      client_session_keep_alive: False
      
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: SNOWFLAKE_INTELLIGENCE_ADMIN
      warehouse: automated_intelligence_wh
      database: automated_intelligence
      schema: dbt_staging
      threads: 4
      client_session_keep_alive: False
